name: Scythe
version: '${project.version}'
main: trxsh.ontop.scythe.Main
api-version: 1.20
authors: [ trxsh ]
description: scythe smp plugin (requires citizens and sentinel)
commands:
  tester:
    description: tester command
    usage: /<command>
  orblevel:
    description: shows a player their orb level.
    usage: /<command>
  loadresources:
    description: loads resource pack.
    usage: /<command>
